# General tasks file for the nagios role
---

# Make sure we have the latest upgrades installed
- name: Install system updates (RedHat based systems)
  yum:
    name: '*'
    state: latest
    update_cache: yes
  ignore_errors: True
  when: ansible_os_family == "RedHat"

# Manage main user
- name: Add and manage the user account
  user:
    name: centos
    state: present
    shell: /bin/bash
    password: "{{ edupert_password }}"
    update_password: 'always'

# Allow password access
- name: Allow ssh password access
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication "
    line: "PasswordAuthentication yes"
  tags: [ 'ps::config' ]
  notify:
    - restart ssh

# Set timezone
- name: Set timezone
  timezone:
    name: "{{ edupert_timezone }}"

# Set hostname
- name: Ensure hostname is well defined
  hostname:
    name: "{{ inventory_hostname }}.{{ edupert_domain }}"

# Manage a local /etc/hosts
- name: Add RFC-1918 and IPv6 address mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK - eduPERT training"
    block: |
        10.0.2.248                              nagios01.{{ edupert_domain }}     nagios01
        2001:620:5ca1:1f0:f816:3eff:fe59:9d08   nagios01.{{ edupert_domain }}     nagios01
        10.0.3.59                               nagios02.{{ edupert_domain }}     nagios02
        2001:620:5ca1:1f0:f816:3eff:fef5:12ba   nagios02.{{ edupert_domain }}     nagios02
        10.0.3.114                              nagios03.{{ edupert_domain }}     nagios03
        2001:620:5ca1:1f0:f816:3eff:fefb:f513   nagios03.{{ edupert_domain }}     nagios03
        10.0.3.73                               nagios04.{{ edupert_domain }}     nagios04
        2001:620:5ca1:1f0:f816:3eff:fee2:8c63   nagios04.{{ edupert_domain }}     nagios04
        10.0.3.7                                nagios05.{{ edupert_domain }}     nagios05
        2001:620:5ca1:1f0:f816:3eff:fe15:34fb   nagios05.{{ edupert_domain }}     nagios05
        10.0.3.23                               nagios06.{{ edupert_domain }}     nagios06
        2001:620:5ca1:1f0:f816:3eff:fe81:1bce   nagios06.{{ edupert_domain }}     nagios06
        10.0.3.11                               nagios07.{{ edupert_domain }}     nagios07
        2001:620:5ca1:1f0:f816:3eff:fe46:6c6c   nagios07.{{ edupert_domain }}     nagios07
        10.0.3.106                              nagios08.{{ edupert_domain }}     nagios08
        2001:620:5ca1:1f0:f816:3eff:fed2:7fe5   nagios08.{{ edupert_domain }}     nagios08
        10.0.0.143                              nagios09.{{ edupert_domain }}     nagios09
        2001:620:5ca1:1f0:f816:3eff:fedc:b1e0   nagios09.{{ edupert_domain }}     nagios09
        10.0.3.109                              nagios10.{{ edupert_domain }}     nagios10
        2001:620:5ca1:1f0:f816:3eff:feef:79eb   nagios10.{{ edupert_domain }}     nagios10

