# This a base playbook to install different perfSONAR flavours on a set of machine
---

# This first task can be replaced by any other provisioning setup
# you're using on your infrastructure.
- name: Bootstrap Ansible on all hosts
  hosts: all
  become: True
  gather_facts: False
  roles:
    - role: bootstrap
      tags: 'bootstrap'

# From here on, these are perfSONAR related tasks
- name: Install and configure perfSONAR testpoint nodes
  hosts: ps-testpoint
  become: True
  roles:
    - role: perfsonar-testpoint

- name: Install and configure perfSONAR toolkit nodes
  hosts: ps-toolkit, ps-toolkit-beta
  become: True
  roles:
    - role: perfsonar-toolkit
      tags: 'perfsonar'

# Some more specific config
- name: Some more configuration of the nodes
  hosts: ps-testpoint, ps-toolkit, ps-toolkit-beta
  become: True
  roles:
    - role: edupert
      tags: 'workshop'

# Nagios VM setup
- name: Nagios VM setup
  hosts: nagios
  become: True
  roles:
    - role: nagios
      tags: [ 'workshop', 'nagios' ]
