# This a base playbook to install different perfSONAR flavours on a set of machines
# and make those ready to be used by participants of some workshop.
---

# This first task can be replaced by any other provisioning setup you're using on your infrastructure.
# Just make sure you can manage the hosts with Ansible
- name: Bootstrap Ansible on all hosts
  hosts: all
  become: True
  gather_facts: False
  roles:
    - role: bootstrap
      tags: 'bootstrap'

# umich bastion setup
- name: bastion security setup
  hosts:
    - techex-umich
  roles:
    - role: epcjr.ansible_role_bastion
  become_method: su

# From here on, these are perfSONAR related tasks
- name: Install and configure perfSONAR testpoint nodes
  hosts: ps-testpoint
  become: True
  roles:
    - role: perfsonar-testpoint
      tags: 'perfsonar'

- name: Install and configure perfSONAR toolkit nodes
  hosts: ps-toolkit
  become: True
  roles:
    - role: perfsonar-toolkit
      tags: 'perfsonar'

# User management, can be replaced by any other provisioning setup you're using on your infrastructure
- name: User and group provisioning on all hosts
  hosts: all
  become: True
  roles:
    - role: users
      tags: 'users'

