# Common users and groups on all systems
---
# perfSONAR group names (add your own groups here)
users_group_names:
  - 'psadmin'
  - 'pssudo'

# User list and configuration (add your own users here)
users_accounts:
  - name: 'antoine'
    group: 'pssudo'
    state: 'present'
    shell: '/bin/bash'
    # Debian/Ubuntu groups
    groups: ['adm', 'staff', 'sudo', 'psadmin', 'pssudo']
    # CentOS 7 groups
    #groups: ['adm', 'systemd-journal', 'wheel', 'psadmin', 'pssudo']
    password: '{{ antoine_password }}'
    sshkeys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDB49XfTrY15sF4KahbxvJ9/w0do4EmvxO54SU4oW2nO/OV1nTKYWwSv5Ru3I6H3DKiQWa5ZO4aMQQd62qXomN9cwrkEgxQc0r4dVPzq2i88cabaWTGE6q6X9/xEllXmfwh22pfQlN92X6wghT3m/z1yzM+XvyXYS8UfC+4Qkh7hJgiyCGnkXqQ3zVvfwzbIf3T4jVikFY4udBwOXXUQs3kZmlJLMLm/1ZZWUcS2guOk9tsDdKxyJxC8+SXrDVFe/2L/7zb1QJ0IqsHCbwT3Q2zuN5XVHtHpi0bo+TNSfVbGsPi+CzZoJRVuhL1h2F9RHREXBvMoVuWYYg0dOSZapPkieaUTqd/YcbnhRPWE+56pH2sW2OW/9iR7PYUeYtceyXjfXm4ItLMHLf2Nh66wVKniVr0f+1XCrUsIMtsve5qJEiOIvONPUWFjB+4KBxuNIrZFCsE0f4Q0aRlsDXUsruWd0bI3WtsvNW7on3yGlJWxxizS04Qf9IP5DBeGw5Wq4/blC2/rCsaMuWpKZii6ltv6Qtw7mPZ/h9MpP/Bu77cxxtNaJ2WxOn8+3lkrWYF8mabRSpPu3cCq0Syx5NZSRMlbyxmlvo1PBTU1wq/i7LI1pPf5ifRZAvvBnsicRUz+htyun2CqZ+JUq+qCravu9GtXn+QBoU9yfkjjVmEp+BkhQ== antoine@4096'
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIj9NP9UYLvT3L1eQStkEN/+/AuZAxQI7SspaHg6cOxc antoine@2017'
      - 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEx1jvLd80HykQPQv0yxGy90w9mWfqrBSXpej51FrKxhf2jIJL+Jtpxf5nBQ+7fpNqt/SHSUeJpP6QzI+9J3DoQ= antoine@mobile'
    dotfiles_repo: 'https://github.com/tonin/osx.dotfiles'
    dotfiles_dest: '~/.config/dotfiles'
    dotfiles_command: '~/.config/dotfiles/deploy.sh'

# Additional packages to install on all nodes (customise at your will)
users_additional_packages:
    # gnuplot is needed by pscheduler plot-schedule command
  - gnuplot
  - man
  - screen
  - vim
    # Only on Debian/Ubuntu (TODO: move to specific file)
  - locales-all

